if has("syntax")
	syntax on
endif

" backup
set nowritebackup
set nobackup

" searching
set ignorecase
set smartcase
set wrapscan
set incsearch
set hlsearch

set number
set title
set ambiwidth=double

" indent
set tabstop=2
set smartindent
set autoindent
set shiftwidth=2

set list
set listchars=tab:»-,trail:-
set nrformats-=octal
set hidden
set history=50
set virtualedit=block
set whichwrap=b,s,[,],<,>
set backspace=indent,eol,start

source ~/.vim/plug.vim

set omnifunc=github_complete#complete
let g:neocomplete#enable_at_startup=1
let g:github_complete_enable_neocomplete=1
let g:github_complete_emoji_japanese_workaround=1
let g:neocomplete#sources = {
	\ '_': ['file', 'tag', 'vim', 'dictionary', 'omni', 'member', 'syntax', 'include', 'github_emoji']
\}

set background=dark
colorscheme Tomorrow-Night-Bright

nmap <silent><C-u><C-u> :<C-u>Unite file<CR>
au FileType unite nmap <silent><buffer><Esc><Esc> <Esc>q
